trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: GitVersion@5
  inputs:
    runtime: 'core'
- task: CmdLine@2
  inputs:
    script: 'printenv'
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'FlowR/FlowR.sln'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'FlowR/FlowR.Tests/FlowR.Tests.csproj'
- task: DotNetCoreCLI@2
  condition: succeeded()
  inputs:
    command: 'pack'
    packagesToPack: 'FlowR/FlowR/FlowR.csproj'
    packDirectory: '$(Build.ArtifactStagingDirectory)'
    nobuild: true
    versioningScheme: 'off'
    versionEnvVar: 'GITVERSION_NUGETVERSION'

